// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isAndroidMobile = require('../unbinded/is_android_mobile')
module.exports = function isAndroidMobile () {
  return _isAndroidMobile(navigator.userAgent)
}
