// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isAndroid = require('../unbinded/is_android')
module.exports = function isAndroid () {
  return _isAndroid(navigator.userAgent)
}
