// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isLinux = require('../unbinded/is_linux')
module.exports = function isLinux () {
  return _isLinux(navigator.userAgent)
}
