// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isWindows = require('../unbinded/is_windows')
module.exports = function isWindows () {
  return _isWindows(navigator.userAgent)
}
