// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _whichOS = require('../unbinded/which_os')
module.exports = function whichOS () {
  return _whichOS(navigator.userAgent)
}
