// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _whichBrowserVersion = require('../unbinded/which_browser_version')
module.exports = function whichBrowserVersion () {
  return _whichBrowserVersion(navigator.userAgent)
}
