// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isWindowsPhone = require('../unbinded/is_windows_phone')
module.exports = function isWindowsPhone () {
  return _isWindowsPhone(navigator.userAgent)
}
