// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isFirefox = require('../unbinded/is_firefox')
module.exports = function isFirefox () {
  return _isFirefox(navigator.userAgent)
}
