// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isEdge = require('../unbinded/is_edge')
module.exports = function isEdge () {
  return _isEdge(navigator.userAgent)
}
