// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isIpad = require('../unbinded/is_ipad')
module.exports = function isIpad () {
  return _isIpad(navigator.userAgent)
}
