// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _whichBrowser = require('../unbinded/which_browser')
module.exports = function whichBrowser () {
  return _whichBrowser(navigator.userAgent)
}
