// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isIphone = require('../unbinded/is_iphone')
module.exports = function isIphone () {
  return _isIphone(navigator.userAgent)
}
