// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isMobile = require('../unbinded/is_mobile')
module.exports = function isMobile () {
  return _isMobile(navigator.userAgent)
}
