const fsp = require('fs-promise')
const listFns = require('./_lib/list_fns')

Promise.all(listFns().map((fn) => {
    const bindedPath = fn.fullPath.replace('unbinded', 'binded')
    const bindedDirPath = bindedPath.replace(/\/index.js$/, '')
    const relativeUnbindedPath = fn.fullPath
      .replace('./src', '..')
      .replace(/\/index.js$/, '')

    return fsp.mkdirp(bindedDirPath)
      .then(() => {
        return fsp.writeFile(bindedPath, [
          "// XXX: This file is generated by a script, don't edit it manually.",
          "//      Please see `npm run build-binded-fns` command.",
          `const _${fn.name} = require('${relativeUnbindedPath}')`,
          `module.exports = function ${fn.name} () {`,
          `  return _${fn.name}(navigator.userAgent)`,
          "}\n"
        ].join('\n'))
      })
  }))
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
