const fsp = require('fs-promise')
const listFns = require('./_lib/list_fns')

Promise.all(listFns().map((fn) => {
  const bindedDirPath = fn.bindedPath.replace(/\/index.js$/, '')
  const relativeUnbindedPath = fn.unboundPath
    .replace('./src', '../..')
    .replace(/\/index.js$/, '')

  return fsp.mkdirp(bindedDirPath)
    .then(() => {
      return fsp.writeFile(fn.bindedPath, [
        "// XXX: This file is generated by a script, don't edit it manually.",
        '//      Please see `npm run build-binded` command.',
        `module.exports = require('${relativeUnbindedPath}')(typeof navigator === 'object' && navigator ? navigator.userAgent : '')\n`
      ].join('\n'))
    })
}))
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
