// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded` command.
module.exports = require('../../unbound/is_linux_fedora')(typeof navigator === 'object' && navigator ? navigator.userAgent : '')
