// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isOpera = require('../unbinded/is_opera')
module.exports = function isOpera () {
  return _isOpera(navigator.userAgent)
}
