// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isMac = require('../unbinded/is_mac')
module.exports = function isMac () {
  return _isMac(navigator.userAgent)
}
