// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isChrome = require('../unbinded/is_chrome')
module.exports = function isChrome () {
  return _isChrome(navigator.userAgent)
}
