// XXX: This file is generated by a script, don't edit it manually.
//      Please see `npm run build-binded-fns` command.
const _isIE = require('../unbinded/is_ie')
module.exports = function isIE () {
  return _isIE(navigator.userAgent)
}
